# CMake generated Testfile for 
# Source directory: /home/btree/Dev/JetsonVideoPlayer/app/tests
# Build directory: /home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ass_renderer]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_ass_renderer")
set_tests_properties([=[test_ass_renderer]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_codecs]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_codecs")
set_tests_properties([=[test_codecs]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_dialogue_index]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_dialogue_index")
set_tests_properties([=[test_dialogue_index]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_hdr_reference]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_hdr_reference")
set_tests_properties([=[test_hdr_reference]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_library]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_library")
set_tests_properties([=[test_library]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_log]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_log")
set_tests_properties([=[test_log]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_loudness]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_loudness")
set_tests_properties([=[test_loudness]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_media_probe]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_media_probe")
set_tests_properties([=[test_media_probe]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_mpris]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_mpris")
set_tests_properties([=[test_mpris]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_network_mount]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_network_mount")
set_tests_properties([=[test_network_mount]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_network_uri]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_network_uri")
set_tests_properties([=[test_network_uri]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_opensubtitles]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_opensubtitles")
set_tests_properties([=[test_opensubtitles]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_qrcode]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_qrcode")
set_tests_properties([=[test_qrcode]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_remote_server]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_remote_server")
set_tests_properties([=[test_remote_server]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_scenes_thumbnails]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_scenes_thumbnails")
set_tests_properties([=[test_scenes_thumbnails]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_settings_storage]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_settings_storage")
set_tests_properties([=[test_settings_storage]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_shortcuts]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_shortcuts")
set_tests_properties([=[test_shortcuts]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_subtitle_parse]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_subtitle_parse")
set_tests_properties([=[test_subtitle_parse]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_subtitle_track]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_subtitle_track")
set_tests_properties([=[test_subtitle_track]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_system_info]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_system_info")
set_tests_properties([=[test_system_info]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_translator]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_translator")
set_tests_properties([=[test_translator]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_whisper]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_whisper")
set_tests_properties([=[test_whisper]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
add_test([=[test_youtube]=] "/home/btree/Dev/JetsonVideoPlayer/app/build-deb/tests/test_youtube")
set_tests_properties([=[test_youtube]=] PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;7;add_test;/home/btree/Dev/JetsonVideoPlayer/app/tests/CMakeLists.txt;0;")
